name: Playwright Tests
on:
  push:
    branches: [main,develop,feautre]
  pull_request:
    branches: [main]
jobs:
  smoke_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: ENV=development npx playwright test --grep=@smoke
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-smoke
          path: playwright-report-smoke/
          retention-days: 30

  regression_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: smoke_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: ENV=development npx playwright test --grep=@regression
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-reggression
          path: playwright-report-reggression/
          retention-days: 30